### ISSUE TITLE
Peer Dependency Warning with @sanity/ui@^1 and Installed Version 2.0.12

### ISSUE THREAD

**Issue by ciruz** [focusreactive/sanity-plugin-inline-svg-input#17]
Hello,

I've encountered a peer dependency warning while working with `@focus-reactive/sanity-plugin-inline-svg-input@1.0.1` in a project. It appears that the plugin expects `@sanity/ui version ^1.x.x`, but the latest is version `2.0.12` , which is leading to the following warning during package installation with pnpm:

```
 WARN  Issues with peer dependencies found
.
└─┬ @focus-reactive/sanity-plugin-inline-svg-input 1.0.1
  └── ✕ unmet peer @sanity/ui@^1: found 2.0.12
```

Just wanted inform you.

**Comment by chenaski** [comment]
Thanks @ciruz, we will soon release a new version with support for `@sanity/ui@2`. We will close the issue after that, so you will be informed.

**Comment by guillermo-avalos** [comment]
Hey @chenaski , any updates? Can't install the plugin for new Studio configs.

**Comment by chenaski** [comment]
Hey @ciruz @guillermo-avalos!

Sorry for the delay, we've just released the new version `@focus-reactive/sanity-plugin-inline-svg-input@1.0.1` with support for both `@sanity/ui@1` and `@sanity/ui@2`.
