### ISSUE TITLE
Add .npmignore

### ISSUE THREAD

**Issue by usulpro** [focusreactive/sanity-plugin-inline-svg-input#2]
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/.gitignore#L60

when package don't have NPM ignore file, the .gitignore will be used instead for packing files into a package. so it wouldn't put dist folder

Actually the better practice is to have a separate .npmignore file and use it to control what files we want to have in our npm package. e.g. src could be ignored

**Comment by chenaski** [comment]
We're using [`files`](https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/main/package.json#L33-L38) to list the files to pack for NPM.
