### ISSUE TITLE
Check before publishing

### ISSUE THREAD

**Issue by usulpro** [focusreactive/sanity-plugin-inline-svg-input#3]
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.config.ts#L8

is it something we need to do?

**Comment by chenaski** [comment]
I think only [`ae-forgotten-export`](https://api-extractor.com/pages/messages/ae-forgotten-export/#docusaurus_skipToContent_fallback) can be useful for us.

The rest of the rules applies to JSDoc, so we don't need them:
- [`ae-incompatible-release-tags`](https://api-extractor.com/pages/messages/ae-incompatible-release-tags/#docusaurus_skipToContent_fallback)
- [`ae-internal-missing-underscore`](https://api-extractor.com/pages/messages/ae-internal-missing-underscore/#docusaurus_skipToContent_fallback)
- [`ae-missing-release-tag`](https://api-extractor.com/pages/messages/ae-missing-release-tag/#docusaurus_skipToContent_fallback)
