### ISSUE TITLE
Double check package.json

### ISSUE THREAD

**Issue by usulpro** [focusreactive/sanity-plugin-inline-svg-input#4]
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L45

is it something we need to run manually? if publishing process isn't just trivial `npm publish` please add a "publish" sections to readme

https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L32

please make sure we have d.ts file generated on the package build step

https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L5

I believe we can add a few more keywords here

https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L74C36-L74C36

minor: do we really need this in dev dependencies?

https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L50C6-L50C15

do we mention in README that we have this feature?

https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/package.json#L78C20-L78C20

does v18 is a requirement?

**Comment by chenaski** [comment]
> is it something we need to run manually? if publishing process isn't just trivial npm publish please add a "publish" sections to readme

No, this runs on [`npm publish`](https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts)

> please make sure we have d.ts file generated on the package build step

✅

> minor: do we really need this in dev dependencies?

By listing a library in both `peerDependencies` and `devDependencies`, you're indicating that it's a requirement for anyone using your package (`peerDependencies`), and also a requirement for developing the package (`devDependencies`). This is a common pattern in scenarios where your package is designed to work with a specific version of a library (like a plugin for a framework), and you also use the same library for development purposes (like testing your plugin with the framework)

> does v18 is a requirement?

[Yes](https://github.com/sanity-io/sanity/blob/next/packages/sanity/package.json#L268)
