### ISSUE TITLE
Dist config usage

### ISSUE THREAD

**Issue by usulpro** [focusreactive/sanity-plugin-inline-svg-input#7]
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/tsconfig.dist.json#L1C2-L1C2

I didn't find any reference to this file. How does it work?

**Comment by chenaski** [comment]
[package.config.ts](https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/main/package.config.ts)
