### ISSUE TITLE
Don't we need to wrap it into a label?

### ISSUE THREAD

**Issue by usulpro** [focusreactive/sanity-plugin-inline-svg-input#8]
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/src/InlineSvgInput.tsx#L129

**Comment by chenaski** [comment]
There's label below:
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/src/InlineSvgInput.tsx#L139
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/src/InlineSvgInput.tsx#L72

**Comment by chenaski** [comment]
There's label below:
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/src/InlineSvgInput.tsx#L139
https://github.com/focusreactive/sanity-plugin-inline-svg-input/blob/cf4aa8e0209debd1657d01bb675f4d439510cdbb/src/InlineSvgInput.tsx#L72
